### PR TITLE
Implement Keyword search

### PR DESCRIPTION
**Pull request by cesidio**
Screenshot 2020-04-14 at 16 21 11

This sets up the new views on the homepage and on the vacancies index page. It implements keyword search with ElasticSearch and keeps old email subscription working. 

All the feature specs updated to work with keyword search.

### CODE REVIEW

**Comment by cesidio** [comment]
This does not relate to any ticket. This is work I have done in my spare time just to prove that with ElasticSearch we can achieve the desired outcome in terms of search services, preserving old functionalities like job alerts.

**Comment by cesidio** [comment]
@tatyree Can you please review this work again, I added a description and an image, I think it will speed up our transition to Algolia as it helps both the client and server rewrite. It refactors feature specs to use the keyword functionality

**Comment by david-mears-dfe** [comment]
> @tatyree Can you please review this work again, I added a description and an image, I think it will speed up our transition to Algolia as it helps both the client and server rewrite. It refactors feature specs to use the keyword functionality

Could you say more about how it helps the client and server rewrites?

**Comment by cesidio** [comment]
> > @tatyree Can you please review this work again, I added a description and an image, I think it will speed up our transition to Algolia as it helps both the client and server rewrite. It refactors feature specs to use the keyword functionality
> 
> Could you say more about how it helps the client and server rewrites?

Sure, it helps the front-end because it prepares the new interface to present the keyword search field and removes subject, job title, working patterns and education phase. It helps the back-end as it refactors the feature specs we had before to use search by keyword. All the specs pass and we preserve old functionalities working. Let me know if you need more information about it.

**Comment by david-mears-dfe** [comment]
The commit message says 'implement keyword search with Elasticsearch'. What's the proposed benefit of this to our current move to Algolia?

**Comment by david-mears-dfe** [comment]
Separately, it seems like there is a *lot* going on in the commit, and I don't understand the changes. There might be some valuable pieces of work inside the commit, but we can't use them, because it's very hard to separate them out - we are forced to either take everything or nothing - and because it's very hard to understand what the changes are, because of the not-very-informative commit message.

Would it be possible to split out the commit into more commits? Then we can at least use parts of the work, if we don't want to use all of it. And it will help to understand what the code changes do and enable us to review it. That would seem to be a minimum requirement for a PR to be approved. Then it's a question of balancing the cost of doing that work, vs. the [proposed benefit](https://github.com/DFE-Digital/teacher-vacancy-service/pull/1490#issuecomment-621885277).

**Comment by cesidio** [comment]
> Separately, it seems like there is a _lot_ going on in the commit, and I don't understand the changes. There might be some valuable pieces of work inside the commit, but we can't use them, because it's very hard to separate them out - we are forced to either take everything or nothing - and because it's very hard to understand what the changes are, because of the not-very-informative commit message.
> 
> Would it be possible to split out the commit into more commits? Then we can at least use parts of the work, if we don't want to use all of it. And it will help to understand what the code changes do and enable us to review it. That would seem to be a minimum requirement for a PR to be approved. Then it's a question of balancing the cost of doing that work, vs. the [proposed benefit](https://github.com/DFE-Digital/teacher-vacancy-service/pull/1490#issuecomment-621885277).



> Separately, it seems like there is a _lot_ going on in the commit, and I don't understand the changes. There might be some valuable pieces of work inside the commit, but we can't use them, because it's very hard to separate them out - we are forced to either take everything or nothing - and because it's very hard to understand what the changes are, because of the not-very-informative commit message.
> 
> Would it be possible to split out the commit into more commits? Then we can at least use parts of the work, if we don't want to use all of it. And it will help to understand what the code changes do and enable us to review it. That would seem to be a minimum requirement for a PR to be approved. Then it's a question of balancing the cost of doing that work, vs. the [proposed benefit](https://github.com/DFE-Digital/teacher-vacancy-service/pull/1490#issuecomment-621885277).

David this is an atomic piece of work, it does not make sense to split it in multiple commits. It removes some code as the front-end search via subject, job title, working pattern and education phase gets removed together with the relative specs. Keword search is implemented in ElasticSearch just by reusing what was done for the subject and job title search. The most valuable piece is the integration specs rewritten for keyword search. When you plugin Algolia you have some specs that have to keep on working like `spec/features/job_seekers_can_search_vacancies_spec.rb`. Or at least need a sensible rewrite of it.

**Comment by tatyree** [comment]
I'm going to go ahead and close this one as we've reached a final decision on this.

**Pull request closed without merging**
