### PR TITLE
update webpacker as outdated yarn dependencies

### PR DESCRIPTION
**Pull request by alexbowen**
no ticket

webpacker needed updating as was conflicting with an outdated dependency in yarn.lock

### CODE REVIEW

**Comment by alexbowen** [comment]
running tests locally suggests that a webpacker config `resolved_paths` is deprecated and has changed to `additional paths` but this change will have to be another PR as i think it introduces a race condition in the build being in the same PR as this

**Comment by alexbowen** [comment]
no it didnt

**Comment by cpjmcquillan** [comment]
What did you change to fix the failing specs?

**Comment by alexbowen** [comment]
the specs were failing because originally i had changed resolved_paths -> additional_paths in the webpacker config. this was because when i ran them locally they all passed but many deprecation warnings. when this key was changed in the PR the failures were saying that webpack couldn't compile but the deprecation warnings disappeared and test passed locally (but i did have to make sure i recompiled assets first).

**Comment by cpjmcquillan** [comment]
> the specs were failing because originally i had changed resolved_paths -> additional_paths in the webpacker config. this was changed because when i ran them locally they all passed but with many deprecation warnings. when this key was changed in the PR the failures were saying that webpack couldn't compile although the deprecation warnings disappeared and test passed locally (but i did have to make sure i recompiled assets first which i dont think the gh action pipeline is able to do).
> 
> Screenshot 2020-08-25 at 12 46 03

Ok, can you add a ticket in for addressing the deprecation warning?

**Review by cpjmcquillan — APPROVED** [review]

**Comment by alexbowen** [comment]
my plan was to imediately see if another PR is able to pass with this key change else yes create ticket 👍

**Pull request merged**
