### PR TITLE
[TEVA-1273] Refactor vacancy organisation indexing

### PR DESCRIPTION
**Pull request by cpjmcquillan**
This PR allows organisation attributes to be indexed when a vacancy has multiple organisations. It also simplifies filtering by indexing education_phases on the vacancy level.

## Jira ticket URL
https://dfedigital.atlassian.net/browse/TEVA-1273

### CODE REVIEW

**Review by david-mears-dfe — COMMENTED** [review]
When this is merged, we will need to instantaneously-ish update the Algolia dashboard configuration. In fact, if I'm not mistaken, it already looks like we forgot to change 'school' to 'organisation' in there.

Screenshot 2020-09-15 at 09 55 29

**Review by david-mears-dfe — COMMENTED** [review]
Would you be able to index a vacancy with this config, and then copy paste the resulting JSON record in here, please?

**Comment by cpjmcquillan** [comment]
> Would you be able to index a vacancy with this config, and then copy paste the resulting JSON record in here, please?

Multiple organisations:
```
{ names: [ "Farnham Heath End", "The Abbey School", "The Park School", "The Ridgeway School" ],
  counties: [ "Surrey" ],
  detailed_school_types: [ "Academy converter", "Academy special converter", "Academy special sponsor led" ],
  group_type: [],
  local_authority: [ "Surrey" ],
  religious_characters: [],
  regions: [ { id: "12fadee6-90e5-4c0c-a35f-fdb9d6a249b0", name: "South East England", code: "J" } ],
  school_types: [ "Academy" ],
  towns: [ "Farnham", "Woking" ] }
```

Single organisation:
```
{ names: [ "Bexleyheath Academy" ],
  counties: [ "Kent" ],
  detailed_school_types: [ "Academy sponsor led" ],
  group_type: [],
  local_authority: [ "Bexley" ],
  religious_characters: [],
  regions: [ { id: "23b0b92f-0679-4587-9533-8ea0716c566e", name: "London", code: "H" } ],
  school_types: [ "Academy" ],
  towns: [ "Bexleyheath" ] }
```

**Review by david-mears-dfe — APPROVED** [review]
Thanks

**Pull request merged**
