### PR TITLE
Update rails to 5.2.4.3

### PR DESCRIPTION
**Pull request by cesidio**

### CODE REVIEW

**Comment by david-mears-dfe** [comment]
So this update forces us to use `session.to_h` etc instead of `session[:whatever]`?

**Comment by cpjmcquillan** [comment]
Similar to @david-mears-dfe question, do we need to change every instance of `session[:some_key]` to `session.to_h['some_key']`?

**Comment by cesidio** [comment]
It is only for the key :session_id, you access all the other keys in the session as you would normally do with []. It might have to do with `append_info_to_payload` method.

**Comment by david-mears-dfe** [comment]
Thank you for addressing this vulnerability by the way!

**Pull request merged**
